#include "PlayerAttackComponent.h"
#include "PauseStateComponent.h"
#include "PauseMenuConfigComponent.h"
#include "OptionStateComponent.h"
#include "OptionMenuConfigComponent.h"

REFLECT_STRUCT_BEGIN(PlayerAttackComponent)
REFLECT_FIELD(spawnOffset),
REFLECT_FIELD(attackSize),
REFLECT_FIELD(visibleTime),
REFLECT_FIELD(attackLayer)
REFLECT_STRUCT_END(PlayerAttackComponent)

REFLECT_STRUCT_BEGIN(PauseStateComponent)
REFLECT_FIELD(isPaused),
REFLECT_FIELD(justEnteredPause),
REFLECT_FIELD(justExitedPause),
REFLECT_FIELD(selectedIndex),
REFLECT_FIELD(itemCount),
REFLECT_FIELD(phase),
REFLECT_FIELD(phaseTime),
REFLECT_FIELD(phaseDuration),
REFLECT_FIELD(requestedAction),
REFLECT_FIELD(isConfirmAnimating),
REFLECT_FIELD(confirmIndex),
REFLECT_FIELD(confirmAnimTime)
REFLECT_STRUCT_END(PauseStateComponent)

REFLECT_STRUCT_BEGIN(PauseMenuConfigComponent)
REFLECT_FIELD(titleStartPosition),
REFLECT_FIELD(titleEndPosition),
REFLECT_FIELD(titleSize),
REFLECT_FIELD(itemBaseStartPosition),
REFLECT_FIELD(itemBaseEndPosition),
REFLECT_FIELD(itemSize),
REFLECT_FIELD(itemSpacing),
REFLECT_FIELD(cursorStartOffset),
REFLECT_FIELD(cursorEndOffset),
REFLECT_FIELD(cursorSize),
REFLECT_FIELD(menuBgStartPosition),
REFLECT_FIELD(menuBgEndPosition),
REFLECT_FIELD(menuBgStartSize),
REFLECT_FIELD(menuBgEndSize),
REFLECT_FIELD(menuBgColor),
REFLECT_FIELD(panelLineStartPosition),
REFLECT_FIELD(panelLineEndPosition),
REFLECT_FIELD(panelLineStartSize),
REFLECT_FIELD(panelLineEndSize),
REFLECT_FIELD(panelLineColor),
REFLECT_FIELD(dimAlpha),
REFLECT_FIELD(openDuration),
REFLECT_FIELD(closeDuration),
REFLECT_FIELD(optionOpenDuration),
REFLECT_FIELD(optionCloseDuration),
REFLECT_FIELD(confirmDuration),
REFLECT_FIELD(selectedScale),
REFLECT_FIELD(confirmScale),
REFLECT_FIELD(easeType),
REFLECT_FIELD(dimLayer),
REFLECT_FIELD(menuBgLayer),
REFLECT_FIELD(panelLineLayer),
REFLECT_FIELD(titleLayer),
REFLECT_FIELD(itemLayer),
REFLECT_FIELD(cursorLayer)
REFLECT_STRUCT_END(PauseMenuConfigComponent)

REFLECT_STRUCT_BEGIN(OptionStateComponent)
REFLECT_FIELD(isOpen),
REFLECT_FIELD(phase),
REFLECT_FIELD(phaseTime),
REFLECT_FIELD(phaseDuration),
REFLECT_FIELD(selectedIndex),
REFLECT_FIELD(itemCount),
REFLECT_FIELD(isEditing),
REFLECT_FIELD(masterVolume),
REFLECT_FIELD(bgmVolume),
REFLECT_FIELD(seVolume),
REFLECT_FIELD(vibrationEnabled)
REFLECT_STRUCT_END(OptionStateComponent)

REFLECT_STRUCT_BEGIN(OptionMenuConfigComponent)
REFLECT_FIELD(dimStartPosition),
REFLECT_FIELD(dimEndPosition),
REFLECT_FIELD(dimSize),
REFLECT_FIELD(dimColor),
REFLECT_FIELD(bgStartPosition),
REFLECT_FIELD(bgEndPosition),
REFLECT_FIELD(bgStartSize),
REFLECT_FIELD(bgEndSize),
REFLECT_FIELD(bgColor),
REFLECT_FIELD(lineStartPosition),
REFLECT_FIELD(lineEndPosition),
REFLECT_FIELD(lineSize),
REFLECT_FIELD(lineColor),
REFLECT_FIELD(itemBaseStartPosition),
REFLECT_FIELD(itemBaseEndPosition),
REFLECT_FIELD(itemSize),
REFLECT_FIELD(itemSpacing),
REFLECT_FIELD(itemColor),
REFLECT_FIELD(selectedItemColor),
REFLECT_FIELD(barOffset),
REFLECT_FIELD(barBaseSize),
REFLECT_FIELD(barFillMinSize),
REFLECT_FIELD(barBaseColor),
REFLECT_FIELD(barFillColor),
REFLECT_FIELD(toggleOffset),
REFLECT_FIELD(toggleSize),
REFLECT_FIELD(toggleOnColor),
REFLECT_FIELD(toggleOffColor),
REFLECT_FIELD(openDuration),
REFLECT_FIELD(closeDuration),
REFLECT_FIELD(volumeStep),
REFLECT_FIELD(dimLayer),
REFLECT_FIELD(bgLayer),
REFLECT_FIELD(lineLayer),
REFLECT_FIELD(itemLayer),
REFLECT_FIELD(barBaseLayer),
REFLECT_FIELD(barFillLayer),
REFLECT_FIELD(toggleLayer)
REFLECT_STRUCT_END(OptionMenuConfigComponent)
