#include "RabbitdokuTag.h"
#include "engine/NoEngine.h"

REFLECT_STRUCT_BEGIN(BlockTag)
REFLECT_STRUCT_END(BlockTag)

REFLECT_STRUCT_BEGIN(SaveTag)
REFLECT_STRUCT_END(SaveTag)

REFLECT_STRUCT_BEGIN(GimmickTag)
REFLECT_STRUCT_END(GimmickTag)

REFLECT_STRUCT_BEGIN(EnemyTag)
REFLECT_STRUCT_END(EnemyTag)

REFLECT_STRUCT_BEGIN(RoomTag)
REFLECT_FIELD(max),
REFLECT_FIELD(min)
REFLECT_STRUCT_END(RoomTag)

REFLECT_STRUCT_BEGIN(TransitionInTag)
REFLECT_STRUCT_END(TransitionInTag)


REFLECT_STRUCT_BEGIN(BackgroundTag)
REFLECT_STRUCT_END(BackgroundTag)

REFLECT_STRUCT_BEGIN(SoftlyMoveComponent)
REFLECT_FIELD(t),
REFLECT_FIELD(moveSpeed),
REFLECT_FIELD(amplitude)
REFLECT_STRUCT_END(SoftlyMoveComponent)

REFLECT_STRUCT_BEGIN(SpringComponent)
REFLECT_FIELD(force)
REFLECT_STRUCT_END(SpringComponent)


REFLECT_STRUCT_BEGIN(CollapseBlockComponent)
REFLECT_FIELD(collapseTime)
REFLECT_STRUCT_END(CollapseBlockComponent)


REFLECT_STRUCT_BEGIN(ReplenisherTag)
REFLECT_STRUCT_END(ReplenisherTag)

REFLECT_STRUCT_BEGIN(DoorComponent)
REFLECT_FIELD(stageName)
REFLECT_STRUCT_END(DoorComponent)

REFLECT_STRUCT_BEGIN(ClearItemComponent)
REFLECT_STRUCT_END(ClearItemComponent)