#include "PauseMenuConfigComponent.h"



REFLECT_STRUCT_BEGIN(PauseMenuConfigComponent)
REFLECT_FIELD(titleStartPosition),
REFLECT_FIELD(titleEndPosition),
REFLECT_FIELD(titleSize),
REFLECT_FIELD(itemBaseStartPosition),
REFLECT_FIELD(itemBaseEndPosition),
REFLECT_FIELD(itemSize),
REFLECT_FIELD(itemSpacing),
REFLECT_FIELD(cursorStartOffset),
REFLECT_FIELD(cursorEndOffset),
REFLECT_FIELD(cursorSize),
REFLECT_FIELD(menuBgStartPosition),
REFLECT_FIELD(menuBgEndPosition),
REFLECT_FIELD(menuBgStartSize),
REFLECT_FIELD(menuBgEndSize),
REFLECT_FIELD(menuBgColor),
REFLECT_FIELD(panelLineStartPosition),
REFLECT_FIELD(panelLineEndPosition),
REFLECT_FIELD(panelLineStartSize),
REFLECT_FIELD(panelLineEndSize),
REFLECT_FIELD(panelLineColor),
REFLECT_FIELD(dimAlpha),
REFLECT_FIELD(openDuration),
REFLECT_FIELD(closeDuration),
REFLECT_FIELD(optionOpenDuration),
REFLECT_FIELD(optionCloseDuration),
REFLECT_FIELD(confirmDuration),
REFLECT_FIELD(selectedScale),
REFLECT_FIELD(confirmScale),
REFLECT_FIELD(easeType),
REFLECT_FIELD(dimLayer),
REFLECT_FIELD(menuBgLayer),
REFLECT_FIELD(panelLineLayer),
REFLECT_FIELD(titleLayer),
REFLECT_FIELD(itemLayer),
REFLECT_FIELD(cursorLayer)
REFLECT_STRUCT_END(PauseMenuConfigComponent)